apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      containers:
      - name: falco
        image: falcosecurity/falco:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: dev
          mountPath: /host/dev
          readOnly: true
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: proc
        hostPath:
          path: /proc
      - name: dev
        hostPath:
          path: /dev
